#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


# This check calls the program that generates the inventory data for
# the <<<nest>>> portion. It passes the only wato configured parameter.
# access_token, which is used to contact nest and get the entire structure
# of managed devices

# Each section returned by the special agent is used by the other service checks
# <<<nest_thermostat>>> or <<<nest_smokealarm>>>

def agent_nest_arguments(params, hostname, ipaddress):
    args = ''

    args += quote_shell_string(params[0])

    return args

special_agent_info['nest'] = agent_nest_arguments
