#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


# Pulls values from the <<<nest_thermostat>>> section of the special agent
# "agent_nest" in the same checks directory
# Uses values to determine name and overall status of the device (not
# the read values of humidity and such)


# line[0].find("Thermostat") != -1 is needed to not take the others into account (Structure and Protect)
def nest_thermostat_parse(info):
    thermostats = {}
    for line in info:
        if line[0].startswith('[') and line[0].find("Thermostat") != -1:
            name = line[0][1:-1]
            thermostat = {}
            thermostats[name] = thermostat
        else:
            key, value = line
            if key in ["is_online", "has_leaf"]:
                value = value.lower() == "true"
            elif key in ["unique_id", "software_version", "temperature_scale"]:
                value = str(value)
            elif key in ["last_connected"]:
                value = str(value)
            thermostat[key] = value
    return thermostats


def inventory_nest_thermostat(info):
    thermostats = nest_thermostat_parse(info)
    return [(name, {}) for name in thermostats]


def check_nest_thermostat(item, params, info):
    thermostats = nest_thermostat_parse(info)
    if item not in thermostats:
        return 3, "Thermostat does not exist"
    thermostat = thermostats[item]

    infotext = ""
    perfdata = ""

    if thermostat["is_online"]:
        infotext += "Nest Thermostat Online, Version: %s" % \
                    (thermostat["software_version"])
        if thermostat["has_leaf"]:
            perfdata = [("leaf", 1)]
        else:
            perfdata = [("leaf", -1)]
        return (0, infotext, perfdata)
    else:
        infotext += "Nest Thermostat Offline, Version: %s" % (thermostat["software_version"])
        perfdata = [("leaf", 0)]
        return (1, infotext)


check_info["nest_thermostat"] = {
    'check_function': check_nest_thermostat,
    'inventory_function': inventory_nest_thermostat,
    'service_description': 'Thermostat %s',
    'group': 'nest_thermostat',
    'has_perfdata': True,
}