#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


# Pulls values from the <<<nest_structure>>> section of the special agent
# "agent_nest" in the same checks directory
# Uses is_away to determine if someone is in the building

# line[0].find("Structure") != -1 is needed to not take the others into account (Thermostat and Protect)
def nest_structure_parse(info):
    structures = {}
    for line in info:
        if line[0].startswith('[') and line[0].find("Structure") != -1:
            name = line[0][1:-1]
            structure = {}
            structures[name] = structure
        else:
            key, value = line
            if key in ["is_away"]:
                value = value.lower() == "true"
            elif key in ["name", "postal_code", "country_code"]:
                value = str(value)
            structure[key] = value
    return structures


def inventory_nest_structure(info):
    structures = nest_structure_parse(info)
    return [(name, {}) for name in structures]


def check_nest_structure(item, params, info):
    structures = nest_structure_parse(info)
    if item not in structures:
        return 3, "Structure does not exist"
    structure = structures[item]

    infotext = ""
	
# Uses the away status to see if there is anyone in the building
    if structure["is_away"]:
        infotext += "No one present in the building"
        return (0, infotext)
    else:
	    infotext += "Away status changed, someone has entered the building"
        return (2, infotext)


check_info["nest_structure"] = {
    'check_function': check_nest_structure,
    'inventory_function': inventory_nest_structure,
    'service_description': 'Structure %s',
    'group': 'nest_structure',
    'has_perfdata': False,
}