#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


# Pulls values from the <<<nest_smoke_co_alarm>>> section of the special agent
# "agent_nest" in the same checks directory
# Uses values to determine name and overall status of the device (not
# the read values of humidity and such)

# line[0].find("Protect") != -1 is needed to not take the others into account (Thermostat and Structure)
def nest_smoke_co_alarm_parse(info):
    smoke_co_alarms = {}
    for line in info: 
        if line[0].startswith('[') and line[0].find("Protect") != -1:
            name = line[0][1:-1]
            smoke_co_alarm = {}
            smoke_co_alarms[name] = smoke_co_alarm
        else:
            key, value = line
            if key in ["is_online"]:
                value = value.lower() == "true"
            elif key in ["unique_id", "software_version", "battery_health"]:
                value = str(value)
            elif key in ["last_connected" ]:
                value = str(value)
            smoke_co_alarm[key] = value
    return smoke_co_alarms

def inventory_nest_smoke_co_alarm(info):
    smoke_co_alarms = nest_smoke_co_alarm_parse(info)
    return [ (name, {}) for name in smoke_co_alarms ]

def check_nest_smoke_co_alarm(item, params, info):
    smoke_co_alarms = nest_smoke_co_alarm_parse(info)
    if item not in smoke_co_alarms:
        return 3, "Smoke Alarm does not exist"
    smoke_co_alarm = smoke_co_alarms[item]
    
    infotext = ""
    perfdata = ""

    if smoke_co_alarm["is_online"]:
        infotext += "Nest Smoke Alarm Online"
        if smoke_co_alarm["battery_health"] == 'ok':
            perfdata = [ ( "battery_health", 1) ]
        else:
            perfdata = [ ( "battery_health", -1) ]
        return (0, infotext, perfdata)
    else:
        infotext += "Nest Smoke Alarm Offline"
        perfdata = [ ("battery_health", 0) ]
        return (1, infotext)

check_info["nest_smoke_co_alarm"] = {
    'check_function':        check_nest_smoke_co_alarm,
    'inventory_function':    inventory_nest_smoke_co_alarm,
    'service_description':   'Smoke Alarm %s',
    'group':                 'nest_smoke_co_alarm',
    'has_perfdata':          True,
}