#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2014 Adams Technology Consulting
#          Gavin Adams <me@gavinadams.org>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Pulls values from the <<<nest_structure>>> section of the special agent
# "agent_nest" in the same checks directory
# Uses is_away to determine if someone is in the building

def nest_structure_parse(info):
    structures = {}
    for line in info:
        if line[0].startswith('[') and line[0].find("Structure") != -1:
            name = line[0][1:-1]
            structure = {}
            structures[name] = structure
        else:
            key, value = line
            if key in ["is_away"]:
                value = value.lower() == "true"
            elif key in ["name", "postal_code", "country_code"]:
                value = str(value)
            structure[key] = value
    return structures


def inventory_nest_structure(info):
    structures = nest_structure_parse(info)
    return [(name, {}) for name in structures]


def check_nest_structure(item, params, info):
    structures = nest_structure_parse(info)
    if item not in structures:
        return 3, "Structure does not exist"
    structure = structures[item]

    infotext = ""

    if structure["is_away"]:
        infotext += "No one present in the building"
        return (0, infotext)
    else:
	    infotext += "Away status changed, someone has entered the building"
        return (2, infotext)


check_info["nest_structure"] = {
    'check_function': check_nest_structure,
    'inventory_function': inventory_nest_structure,
    'service_description': 'Structure %s',
    'group': 'nest_structure',
    'has_perfdata': False,
}