#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2014 Adams Technology Consulting
#          Gavin Adams <me@gavinadams.org>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Pulls values from the <<<rbpi_humidity>>> section of the special agent
# "agent_rbpi" in the same checks directory

# Creates humidity checks for all reported devices

# Default is 50% humidity. Like the temperature, warning and critical
# values are 10% and 15% beyond the default

rbpi_humidity_default_levels = (0, 10, 60, 65)


def rbpi_humidity_parse(info):
    devices = {}
    name = "RBPi"
    device = {}
    devices[name] = device
    for line in info:
        key, value = line
        if key in ["rbpiHumidity" ]:
            value = float(value)			
            device[key] = value
    return devices

def inventory_rbpi_humidity(info):
    devices = rbpi_humidity_parse(info)
    return [ (name, {}, "rbpi_humidity_default_levels") for name in devices ]

def check_rbpi_humidity(item, params, info):

    critlow, warnlow, warnhigh, crithigh = params

    # set warn and crit as both values, low and high, separated by colon
    # perfdata and PNP4Nagios should pick this up

    warn = "%d:%d" % (warnlow, warnhigh)
    crit = "%d:%d" % (critlow, crithigh)
    
    # Process inventory for datasource check
    devices = rbpi_humidity_parse(info)
    device = devices[item]
    
    infotext = ""
    humidity = 0

    humidity = float(device["rbpiHumidity"])
    infotext += "%d%% RH" % humidity
    perfdata = [ ("humidity", humidity, warn, crit) ]

    if humidity <= critlow or humidity >= crithigh:
        return (2, "CRITICAL - Humidity is %s" % infotext, perfdata)
    if humidity <= warnlow or humidity >= warnhigh:
        return (1, "WARNING - Humidity is %s" % infotext, perfdata)
    else:
        return (0, "OK - Humidity is %s" % infotext, perfdata)

check_info["rbpi_humidity"] = {
    'check_function':        check_rbpi_humidity,
    'inventory_function':    inventory_rbpi_humidity,
    'service_description':   'Humidity %s',
    'group':                 'rbpi_humidity',
    'has_perfdata':          True,
}

