#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

#
# (c) 2014 Adams Technology Consulting
#          Gavin Adams <me@gavinadams.org>
#

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Pulls values from the <<<rbpi_db>>> section

def rbpi_db_parse(info):
    devices = {}
    name = "RBPi"
    device = {}
    devices[name] = device
    for line in info:
        key, value = line
        if key in ["rbpiDb" ]:
            value = str(value)
            device[key] = value
    return devices

def inventory_rbpi_db(info):
    devices = rbpi_db_parse(info)
    return [ (name, {}) for name in devices ]

def check_rbpi_db(item, params, info):

    # Process inventory for datasource check
    devices = rbpi_db_parse(info)
    device = devices[item]

    infotext = ""
    db = False

    db = str(device["rbpiDb"])

    if db is False:
        return (1, "WARNING - No Database Connection")
    else:
        return (0, "OK - Db connection OK")

check_info["rbpi_db"] = {
    'check_function':        check_rbpi_db,
    'inventory_function':    inventory_rbpi_db,
    'service_description':   'Database %s',
    'group':                 'rbpi_db',
    'has_perfdata':          False,
}
